import Head from "next/head";
import AboutSection from "../components/sections/AboutSection";

const About = () => {
	return (
		<div>
			<Head>
				<title>Riyeko</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<AboutSection />
			</main>
		</div>
	);
};

export default About;
