import Head from "next/head";
import AboutSection from "../components/sections/AboutSection";
import HeroSection from "../components/sections/HeroSection";
import RoadmapSection from "../components/sections/RoadmapSection";
import StreetSection from "../components/sections/StreetSection";
import TeamSection from "../components/sections/TeamSection";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Riyeko</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<HeroSection />
				<AboutSection />
				{/* <RoadmapSection /> */}
				<TeamSection />
				<StreetSection />
			</main>
		</div>
	);
}
