import Head from "next/head";
import HeroSection from "../components/sections/HeroSection";

const Home = () => {
	return (
		<div>
			<Head>
				<title>Riyeko</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<HeroSection />
			</main>
		</div>
	);
};

Home.commonHeader = true;
export default Home;
