import Head from "next/head";
import StreetSection from "../components/sections/StreetSection";

const Street = () => {
	return (
		<div>
			<Head>
				<title>Riyeko</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<StreetSection />
			</main>
		</div>
	);
};

export default Street;
