import Head from "next/head";
import TeamSection from "../components/sections/TeamSection";

const Team = () => {
	return (
		<div>
			<Head>
				<title>Riyeko</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<TeamSection />
			</main>
		</div>
	);
};

export default Team;
